name: Maravillas360
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.8
  dots_indicator: ^2.1.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_point_tab_bar: ^0.2.0
  iconsax: ^0.0.8
  ionicons: ^0.2.2
  rive: ^0.9.1
  flutter_svg: ^1.1.6
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  get: ^4.6.5
  http: ^0.13.6
  flutter_lints: ^4.0.0
  build_runner: ^2.1.0

flutter:
  uses-material-design: true
  generate: true
  

  assets:
    - assets/
    - assets/images/friends/
    - assets/images/posts/
    - assets/images/saved/
    - assets/images/story/
    - assets/images/flags/
    - assets/avaters/
    - assets/Backgrounds/
    - assets/icons/
    - assets/RiveAssets/

  fonts:
    - family: Ubuntu-Regular
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf

