name: Maravillas360
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"
  



dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.8
  dots_indicator: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_point_tab_bar: ^0.2.0
  iconsax: ^0.0.8
  ionicons: ^0.2.2
  rive: ^0.13.15
  flutter_svg: ^2.0.11
  change_app_package_name: ^1.4.0

  provider: ^6.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  share_plus: ^10.1.1
  store_redirect: ^2.0.1
  url_launcher: ^6.1.5
  shared_preferences: ^2.0.15
  flutter_phone_direct_caller: ^2.1.1
  connectivity_plus: ^6.1.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0

  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.3
  flutter_facebook_auth: ^7.1.1
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.0
  
  badges: ^3.1.2
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  fluttertoast: ^8.0.9
  circle_nav_bar: ^2.1.1
  dotted_border: ^2.0.0+2
  delayed_display: ^2.0.0
  carousel_slider: ^5.0.0
  swipeable_tile: ^2.0.0+1 #dissmissable
  intl_phone_field: ^3.0.0
  top_snackbar_flutter: ^3.1.0
  date_picker_timeline: ^1.2.3
  easy_localization: ^3.0.1
  readmore: ^3.0.0
  flutter_widget_from_html: ^0.15.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  get: ^4.6.5
  http: ^1.2.2
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
      - assets/
      - assets/images/friends/
      - assets/images/posts/
      - assets/images/saved/
      - assets/images/story/
      - assets/images/flags/
      - assets/avaters/
      - assets/Backgrounds/
      - assets/icons/
      - assets/RiveAssets/

  fonts:
    - family: Ubuntu-Regular
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
